// <auto-generated />
using System;
using CloudPRNT_Solution.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudPRNT_Solution.Migrations.DeviceQueue
{
    [DbContext(typeof(DeviceTableContext))]
    partial class DeviceQueueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("CloudPRNT_Solution.Models.DeviceTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DotWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastPoll")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterMac")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QueueID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceTable");
                });
#pragma warning restore 612, 618
        }
    }
}
