// <auto-generated />
using System;
using CloudPRNT_Solution.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudPRNT_Solution.Migrations
{
    [DbContext(typeof(PrintQueueContext))]
    partial class PrintQueueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("CloudPRNT_Solution.Models.PrintQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterMac")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrintQueue");
                });
#pragma warning restore 612, 618
        }
    }
}
